### ISSUE TITLE
Fail to build with libxml >= 2.12.0

### ISSUE THREAD

**Issue by marillat** [karlheyes/icecast-kh#471]
Debian unstable amd64

The following commit made it into 2.12.0 changed the const-ness of
xmlError pointers:

  https://gitlab.gnome.org/GNOME/libxml2/-/commit/61034116d0a3c8b295c6137956adc3ae55720711

```
gcc -DHAVE_CONFIG_H -I. -I..  -Wall -ffast-math -fsigned-char -I/usr/include/libxml2 -I/usr/include -Wdate-time -D_FORTIFY_SOURCE=2  -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/build/icecast2-dmo-2.4.0kh22=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -c -o auth_url.o auth_url.c
event.c: In function 'event_config_read':
event.c:47:45: error: passing argument 2 of 'xmlSetStructuredErrorFunc' from incompatible pointer type [-Wincompatible-pointer-types]
   47 |     xmlSetStructuredErrorFunc ("conf/file", config_xml_parse_failure);
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                             |
      |                                             void (*)(void *, xmlError *) {aka void (*)(void *, struct _xmlError *)}
In file included from /usr/include/libxml2/libxml/valid.h:16,
                 from /usr/include/libxml2/libxml/parser.h:20,
                 from /usr/include/libxml2/libxml/tree.h:17,
                 from auth.h:23,
                 from cfgfile.h:33,
                 from event.c:20:
/usr/include/libxml2/libxml/xmlerror.h:905:57: note: expected 'xmlStructuredErrorFunc' {aka 'void (*)(void *, const struct _xmlError *)'} but argument is of type 'void (*)(void *, xmlError *)' {aka 'void (*)(void *, struct _xmlError *)'}
  905 |                                  xmlStructuredErrorFunc handler);
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
make[4]: *** [Makefile:743: event.o] Error 1
make[4]: *** Waiting for unfinished jobs....
xslt.c: In function 'xslt_initialize':
xslt.c:222:5: warning: 'xmlSubstituteEntitiesDefault' is deprecated [-Wdeprecated-declarations]
  222 |     xmlSubstituteEntitiesDefault(1);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/libxml2/libxml/tree.h:17,
                 from /usr/include/libxml2/libxml/debugXML.h:15,
                 from xslt.c:25:
/usr/include/libxml2/libxml/parser.h:1106:17: note: declared here
 1106 |                 xmlSubstituteEntitiesDefault(int val);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
xslt.c:223:5: warning: '__xmlLoadExtDtdDefaultValue' is deprecated [-Wdeprecated-declarations]
  223 |     xmlLoadExtDtdDefaultValue = 1;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/libxml2/libxml/parser.h:1034:16: note: declared here
 1034 | XMLPUBFUN int *__xmlLoadExtDtdDefaultValue(void);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
xslt.c: In function 'xslt_update':
xslt.c:568:44: error: passing argument 2 of 'xmlSetStructuredErrorFunc' from incompatible pointer type [-Wincompatible-pointer-types]
  568 |     xmlSetStructuredErrorFunc ("xsl/file", config_xml_parse_failure);
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                            |
      |                                            void (*)(void *, xmlError *) {aka void (*)(void *, struct _xmlError *)}
In file included from /usr/include/libxml2/libxml/valid.h:16,
                 from /usr/include/libxml2/libxml/parser.h:20:
/usr/include/libxml2/libxml/xmlerror.h:905:57: note: expected 'xmlStructuredErrorFunc' {aka 'void (*)(void *, const struct _xmlError *)'} but argument is of type 'void (*)(void *, xmlError *)' {aka 'void (*)(void *, struct _xmlError *)'}
  905 |                                  xmlStructuredErrorFunc handler);
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
make[4]: *** [Makefile:743: xslt.o] Error 1
cfgfile.c: In function 'config_parse_file':
cfgfile.c:739:45: error: passing argument 2 of 'xmlSetStructuredErrorFunc' from incompatible pointer type [-Wincompatible-pointer-types]
  739 |     xmlSetStructuredErrorFunc ("conf/file", config_xml_parse_failure);
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                             |
      |                                             void (*)(void *, xmlError *) {aka void (*)(void *, struct _xmlError *)}
In file included from /usr/include/libxml2/libxml/valid.h:16,
                 from /usr/include/libxml2/libxml/parser.h:20,
                 from cfgfile.c:22:
/usr/include/libxml2/libxml/xmlerror.h:905:57: note: expected 'xmlStructuredErrorFunc' {aka 'void (*)(void *, const struct _xmlError *)'} but argument is of type 'void (*)(void *, xmlError *)' {aka 'void (*)(void *, struct _xmlError *)'}
  905 |                                  xmlStructuredErrorFunc handler);
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
make[4]: *** [Makefile:743: cfgfile.o] Error 1
format_mp3.c: In function 'metadata_setup':
format_mp3.c:466:51: error: passing argument 2 of 'xmlSetStructuredErrorFunc' from incompatible pointer type [-Wincompatible-pointer-types]
  466 |         xmlSetStructuredErrorFunc (source->mount, config_xml_parse_failure);
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                                   |
      |                                                   void (*)(void *, xmlError *) {aka void (*)(void *, struct _xmlError *)}
In file included from /usr/include/libxml2/libxml/valid.h:16,
                 from /usr/include/libxml2/libxml/parser.h:20,
                 from /usr/include/libxml2/libxml/tree.h:17,
                 from auth.h:23,
                 from cfgfile.h:33,
                 from source.h:17,
                 from format_mp3.c:33:
/usr/include/libxml2/libxml/xmlerror.h:905:57: note: expected 'xmlStructuredErrorFunc' {aka 'void (*)(void *, const struct _xmlError *)'} but argument is of type 'void (*)(void *, xmlError *)' {aka 'void (*)(void *, struct _xmlError *)'}
  905 |                                  xmlStructuredErrorFunc handler);
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
admin.c: In function 'admin_handle_request':
admin.c:405:50: error: passing argument 2 of 'xmlSetStructuredErrorFunc' from incompatible pointer type [-Wincompatible-pointer-types]
  405 |         xmlSetStructuredErrorFunc ((char*)mount, config_xml_parse_failure);
      |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                                  |
      |                                                  void (*)(void *, xmlError *) {aka void (*)(void *, struct _xmlError *)}
In file included from /usr/include/libxml2/libxml/valid.h:16,
                 from /usr/include/libxml2/libxml/parser.h:20,
                 from admin.c:23:
/usr/include/libxml2/libxml/xmlerror.h:905:57: note: expected 'xmlStructuredErrorFunc' {aka 'void (*)(void *, const struct _xmlError *)'} but argument is of type 'void (*)(void *, xmlError *)' {aka 'void (*)(void *, struct _xmlError *)'}
  905 |                                  xmlStructuredErrorFunc handler);
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
admin.c: In function 'admin_handle_general_request':
admin.c:452:44: error: passing argument 2 of 'xmlSetStructuredErrorFunc' from incompatible pointer type [-Wincompatible-pointer-types]
  452 |     xmlSetStructuredErrorFunc ((char*)uri, config_xml_parse_failure);
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                            |
      |                                            void (*)(void *, xmlError *) {aka void (*)(void *, struct _xmlError *)}
/usr/include/libxml2/libxml/xmlerror.h:905:57: note: expected 'xmlStructuredErrorFunc' {aka 'void (*)(void *, const struct _xmlError *)'} but argument is of type 'void (*)(void *, xmlError *)' {aka 'void (*)(void *, struct _xmlError *)'}
  905 |                                  xmlStructuredErrorFunc handler);
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
make[4]: *** [Makefile:743: admin.o] Error 1
make[4]: *** [Makefile:743: format_mp3.o] Error 1
client.c: In function 'worker_wakeup':
client.c:556:21: warning: ignoring return value of 'write' declared with attribute 'warn_unused_result' [-Wunused-result]
  556 |  #define pipe_write write
      |                     ^
client.c:1039:5: note: in expansion of macro 'pipe_write'
 1039 |     pipe_write (worker->wakeup_fd[1], "W", 1);
      |     ^~~~~~~~~~
client.c: In function 'logger_commits':
client.c:556:21: warning: ignoring return value of 'write' declared with attribute 'warn_unused_result' [-Wunused-result]
  556 |  #define pipe_write write
      |                     ^
client.c:1045:5: note: in expansion of macro 'pipe_write'
 1045 |     pipe_write (logger_fd[1], "L", 1);
      |     ^~~~~~~~~~
make[4]: Leaving directory '/build/icecast2-dmo-2.4.0kh22/src'
```
