### ISSUE TITLE
kh6 doesn't build with libssl 1.1

### ISSUE THREAD

**Issue by marillat** [karlheyes/icecast-kh#182]
Debian unstable amd64, libssl 1.1.0f
New code for DH/ECDH doesn't build with libssl 1.1

````
connection.c: In function ‘get_dh2048’:
connection.c:89:4: error: dereferencing pointer to incomplete type ‘DH {aka struct dh_st}’
  dh->p = BN_bin2bn (dh2048_p, sizeof(dh2048_p), NULL);
````

**Comment by karlheyes** [comment]
Indeed 1.0 was the only one I had, and it looks like the API changed in 1.1.  Does the attached patch build for you?
[a.diff.txt](https://github.com/karlheyes/icecast-kh/files/1312661/a.diff.txt)

karl.

**Comment by marillat** [comment]
Thanks, compile fine.
For the record libssl 1.0 is deprecated in Debian has begun to remove 1.0 
https://release.debian.org/transitions/html/openssl1.0-rm.html

**Comment by leonardder** [comment]
Comfirmed. @karlheyes, would you be able to provide the patch in a new tarball of kh6?

**Comment by marillat** [comment]
I already uploaded kh6 packages with the provided patch.

**Comment by leonardder** [comment]
Looks like this can be closed now kh7 is there.

**Comment by marillat** [comment]
Yes.
